config-version: 2

name: "jaffle_shop"

profile: jaffleshop # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds","jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "target-base"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  jaffle_shop:
    +database: jaffle_seed_db
    +schema: raw


models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
