name: Build
on: [push]
jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: install dbt
        run: |
          pip install dbt-snowflake==1.9.0
          dbt deps

      - name: run dbt
        run: dbt run
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      - name: install metaplane cli
        run: /bin/bash -c "$(curl -fsSL https://cli.metaplane.dev/install.sh)"

      - name: report to metaplane
        if: github.ref == 'refs/heads/main' # only report main branch runs
        run: |
          metaplane import-dbt-run  \
            --connection-id ${{ secrets.MP_CONNECTION_ID }} \
            --project-name my-dbt-core-project \
            --job-name production-run \
            --manifest target/manifest.json \
            --run-results target/run_results.json
        env:
          MP_API_TOKEN: ${{ secrets.MP_API_TOKEN }}

      - name: trigger metaplane pr comments
        if: github.ref != 'refs/heads/main' # provide --commit-sha on non-main branch run
        run: |
          metaplane import-dbt-run  \
            --connection-id ${{ secrets.MP_CONNECTION_ID }} \
            --project-name my-dbt-core-project \
            --job-name branch-run \
            --manifest target/manifest.json \
            --run-results target/run_results.json \
            --commit-sha "${{ github.event.pull_request.head.sha || github.sha }}"
        env:
          MP_API_TOKEN: ${{ secrets.MP_API_TOKEN }}
